--------------------------------------------------------
--  파일이 생성됨 - 토요일-6월-19-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CURRENT_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CURRENT_CUSTOMER" 
   (	"거래처" VARCHAR2(38 BYTE), 
	"실운송비용" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CURRENT_CUSTOMER
SET DEFINE OFF;
Insert into SYSTEM.CURRENT_CUSTOMER ("거래처","실운송비용") values ('(주)민성폐차산업',49900);
Insert into SYSTEM.CURRENT_CUSTOMER ("거래처","실운송비용") values ('주식회사 월드리싸이클링',52100);
--------------------------------------------------------
--  DDL for Index SYS_C0011163
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0011163" ON "SYSTEM"."CURRENT_CUSTOMER" ("거래처") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CURRENT_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CURRENT_CUSTOMER" ADD PRIMARY KEY ("거래처")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
